# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c0a6123285cd9d905943752e604aaf5dcbbe7e77a92e9507608c2f64129d8bba0ad2b8bdc8286ff7ed2c28688fb2464c88c768574c1f1cbecba4870f9901728

test:
  secret_key_base: 5e6ae594a4f57b78733f34dec3e71e1e5b306a4b263c9f2bbddd9797302022697743853b34562b1338d05b40f1b37b9bbbb4d59ebdbb2d236940a2105a0982b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
